// Comprehensive list of banks operating in Indonesia — national commercial,
// sharia, digital, regional development (BPD) and foreign/joint-venture banks.
// `slug` maps to an optional real logo at public/banks/<slug>.png; when that
// file is absent the invoice falls back to a brand-coloured badge. `color` is
// the bank's brand colour used for that badge.

export interface BankInfo {
  name: string
  slug: string
  color?: string
}

export const INDONESIAN_BANKS: BankInfo[] = [
  // ── Bank umum nasional ──
  { name: 'Bank Central Asia (BCA)', slug: 'bca', color: '#1557bf' },
  { name: 'Bank Mandiri', slug: 'mandiri', color: '#003d79' },
  { name: 'Bank Negara Indonesia (BNI)', slug: 'bni', color: '#f05a22' },
  { name: 'Bank Rakyat Indonesia (BRI)', slug: 'bri', color: '#00529c' },
  { name: 'Bank Tabungan Negara (BTN)', slug: 'btn', color: '#002f6c' },
  { name: 'Bank Syariah Indonesia (BSI)', slug: 'bsi', color: '#00a39d' },
  { name: 'Bank CIMB Niaga', slug: 'cimb-niaga', color: '#e01a22' },
  { name: 'Bank CIMB Niaga Syariah', slug: 'cimb-niaga-syariah', color: '#7a1f2b' },
  { name: 'Bank Danamon Indonesia', slug: 'danamon', color: '#ed1c24' },
  { name: 'Bank Permata (PermataBank)', slug: 'permata', color: '#00a79d' },
  { name: 'Bank Pan Indonesia (Panin)', slug: 'panin', color: '#0033a0' },
  { name: 'Bank Maybank Indonesia', slug: 'maybank', color: '#ffc61e' },
  { name: 'Bank OCBC NISP', slug: 'ocbc-nisp', color: '#e30613' },
  { name: 'Bank BTPN', slug: 'btpn', color: '#003da5' },
  { name: 'Bank BTPN Syariah', slug: 'btpn-syariah', color: '#00a6a0' },
  { name: 'Bank Mega', slug: 'mega', color: '#003876' },
  { name: 'Bank Sinarmas', slug: 'sinarmas', color: '#ed1c24' },
  { name: 'KB Bank (Bukopin)', slug: 'kb-bukopin', color: '#fdb913' },
  { name: 'Bank Muamalat Indonesia', slug: 'muamalat', color: '#1b7a6e' },
  { name: 'Bank Mega Syariah', slug: 'mega-syariah', color: '#00693e' },
  { name: 'Bank BCA Syariah', slug: 'bca-syariah', color: '#00539f' },
  { name: 'Bank BCA Digital (blu)', slug: 'blu-bca', color: '#00aeef' },
  { name: 'Bank Jago', slug: 'jago', color: '#ffcc00' },
  { name: 'Bank Jago Syariah', slug: 'jago-syariah', color: '#f7b500' },
  { name: 'Bank Neo Commerce (BNC)', slug: 'neo-commerce', color: '#fdb714' },
  { name: 'Bank Seabank Indonesia', slug: 'seabank', color: '#2b2e8c' },
  { name: 'Allo Bank Indonesia', slug: 'allo', color: '#ee3124' },
  { name: 'Bank Aladin Syariah', slug: 'aladin', color: '#00a9e0' },
  { name: 'Superbank', slug: 'superbank', color: '#111827' },
  { name: 'Krom Bank Indonesia', slug: 'krom', color: '#ff5a00' },
  { name: 'Bank Nationalnobu (Nobu)', slug: 'nobu', color: '#0a2a66' },
  { name: 'Bank Sahabat Sampoerna', slug: 'sampoerna', color: '#c8102e' },
  { name: 'Bank Amar Indonesia', slug: 'amar', color: '#7b2cbf' },
  { name: 'Bank MNC Internasional (Motion)', slug: 'mnc', color: '#e30613' },
  { name: 'Bank Artha Graha Internasional', slug: 'artha-graha', color: '#003a70' },
  { name: 'Bank Mayapada Internasional', slug: 'mayapada', color: '#c8102e' },
  { name: 'Bank Mestika Dharma', slug: 'mestika', color: '#0057a8' },
  { name: 'Bank Ganesha', slug: 'ganesha', color: '#e2001a' },
  { name: 'Bank Ina Perdana', slug: 'ina-perdana', color: '#0a3d91' },
  { name: 'Bank Capital Indonesia', slug: 'capital', color: '#1b3f8b' },
  { name: 'Bank Victoria International', slug: 'victoria', color: '#c8102e' },
  { name: 'Bank Woori Saudara (BWS)', slug: 'woori-saudara', color: '#0067ac' },
  { name: 'Bank Index Selindo', slug: 'index', color: '#004a99' },
  { name: 'Bank Oke Indonesia', slug: 'oke', color: '#00a24b' },
  { name: 'Bank IBK Indonesia', slug: 'ibk', color: '#00539b' },
  { name: 'Bank JTrust Indonesia', slug: 'jtrust', color: '#e60027' },
  { name: 'Bank Multiarta Sentosa', slug: 'multiarta', color: '#1b3f8b' },
  { name: 'Bank Bumi Arta', slug: 'bumi-arta', color: '#0a3d91' },
  { name: 'Bank QNB Indonesia', slug: 'qnb', color: '#7a2e3a' },
  { name: 'Bank Mandiri Taspen', slug: 'mandiri-taspen', color: '#003d79' },
  { name: 'Bank Digital BCA', slug: 'bca-digital', color: '#0060af' },
  { name: 'Bank Fama Internasional', slug: 'fama', color: '#0a3d91' },
  { name: 'Bank Jasa Jakarta', slug: 'jasa-jakarta', color: '#111827' },
  { name: 'Bank Harda Internasional', slug: 'harda', color: '#0a3d91' },
  { name: 'Bank SBI Indonesia', slug: 'sbi', color: '#c8102e' },

  // ── Bank asing & campuran ──
  { name: 'Citibank N.A. Indonesia', slug: 'citibank', color: '#056dae' },
  { name: 'HSBC Indonesia', slug: 'hsbc', color: '#db0011' },
  { name: 'Standard Chartered Bank', slug: 'standard-chartered', color: '#0473ea' },
  { name: 'Bank DBS Indonesia', slug: 'dbs', color: '#dc0028' },
  { name: 'Bank UOB Indonesia', slug: 'uob', color: '#003d7c' },
  { name: 'Bank OCBC Indonesia', slug: 'ocbc', color: '#e30613' },
  { name: 'Bank Commonwealth', slug: 'commonwealth', color: '#e6a100' },
  { name: 'Bank ANZ Indonesia', slug: 'anz', color: '#004165' },
  { name: 'Bank BNP Paribas Indonesia', slug: 'bnp-paribas', color: '#00915a' },
  { name: 'Bank Mizuho Indonesia', slug: 'mizuho', color: '#1c3f94' },
  { name: 'Bank MUFG (Bank of Tokyo-Mitsubishi UFJ)', slug: 'mufg', color: '#e60012' },
  { name: 'Bank SMBC Indonesia', slug: 'smbc', color: '#00a040' },
  { name: 'Bank Resona Perdania', slug: 'resona', color: '#0a3d91' },
  { name: 'Bank CTBC Indonesia', slug: 'ctbc', color: '#c8102e' },
  { name: 'Bank KEB Hana Indonesia', slug: 'keb-hana', color: '#00857a' },
  { name: 'Line Bank (Hana Bank)', slug: 'line-bank', color: '#06c755' },
  { name: 'Bank of China Indonesia', slug: 'boc', color: '#c8102e' },
  { name: 'Bank of India Indonesia', slug: 'boi', color: '#f37021' },
  { name: 'Bank Rabobank Indonesia', slug: 'rabobank', color: '#f76900' },
  { name: 'JP Morgan Chase Indonesia', slug: 'jpmorgan', color: '#5c2d2d' },
  { name: 'Deutsche Bank Indonesia', slug: 'deutsche', color: '#0018a8' },

  // ── Bank Pembangunan Daerah (BPD) ──
  { name: 'Bank DKI', slug: 'dki', color: '#e4002b' },
  { name: 'Bank BJB (Jabar Banten)', slug: 'bjb', color: '#0072bc' },
  { name: 'Bank BJB Syariah', slug: 'bjb-syariah', color: '#00693e' },
  { name: 'Bank Jateng (Jawa Tengah)', slug: 'jateng', color: '#0a3d91' },
  { name: 'Bank Jateng Syariah', slug: 'jateng-syariah', color: '#00693e' },
  { name: 'Bank Jatim (Jawa Timur)', slug: 'jatim', color: '#c8102e' },
  { name: 'Bank BPD DIY (Yogyakarta)', slug: 'bpd-diy', color: '#0a6b3b' },
  { name: 'Bank Sumut', slug: 'sumut', color: '#e30613' },
  { name: 'Bank Nagari (Sumbar)', slug: 'nagari', color: '#0057a8' },
  { name: 'Bank Riau Kepri Syariah', slug: 'riau-kepri', color: '#00693e' },
  { name: 'Bank Sumsel Babel', slug: 'sumsel-babel', color: '#0a3d91' },
  { name: 'Bank Lampung', slug: 'lampung', color: '#0057a8' },
  { name: 'Bank Jambi', slug: 'jambi', color: '#0a6b3b' },
  { name: 'Bank Bengkulu', slug: 'bengkulu', color: '#0057a8' },
  { name: 'Bank Aceh Syariah', slug: 'aceh', color: '#00693e' },
  { name: 'Bank Kalbar (Kalimantan Barat)', slug: 'kalbar', color: '#0057a8' },
  { name: 'Bank Kalsel (Kalimantan Selatan)', slug: 'kalsel', color: '#0a6b3b' },
  { name: 'Bank Kalteng (Kalimantan Tengah)', slug: 'kalteng', color: '#c8102e' },
  { name: 'Bank Kaltimtara (Kalimantan Timur & Utara)', slug: 'kaltimtara', color: '#0057a8' },
  { name: 'Bank Sulselbar (Sulawesi Selatan & Barat)', slug: 'sulselbar', color: '#e30613' },
  { name: 'Bank SulutGo (Sulawesi Utara & Gorontalo)', slug: 'sulutgo', color: '#0057a8' },
  { name: 'Bank Sulteng (Sulawesi Tengah)', slug: 'sulteng', color: '#0a6b3b' },
  { name: 'Bank Sultra (Sulawesi Tenggara)', slug: 'sultra', color: '#0057a8' },
  { name: 'Bank NTB Syariah', slug: 'ntb', color: '#00693e' },
  { name: 'Bank BPD Bali', slug: 'bpd-bali', color: '#c8102e' },
  { name: 'Bank NTT (Nusa Tenggara Timur)', slug: 'ntt', color: '#0057a8' },
  { name: 'Bank Maluku Malut', slug: 'maluku', color: '#0a3d91' },
  { name: 'Bank Papua', slug: 'papua', color: '#0a6b3b' },
  { name: 'Bank Banten', slug: 'banten', color: '#0057a8' },
]

/** Look up a bank by its display name (values come from the same list). */
export function findBank(name: string | null | undefined): BankInfo | null {
  if (!name) return null
  return INDONESIAN_BANKS.find((b) => b.name === name) ?? null
}
